# Generated by Django 2.0.4 on 2018-04-08 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65)),
                ('accountnumber', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=30)),
                ('addressnumber', models.CharField(default=0, max_length=6)),
                ('city', models.CharField(default='', max_length=65)),
                ('state', models.CharField(default='', max_length=30)),
                ('country', models.CharField(default='CHILE', max_length=65, null=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to=settings.AUTH_USER_MODEL)),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='account_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65)),
                ('comments', models.CharField(max_length=65)),
                ('type', models.CharField(choices=[('0', 'RUT'), ('1', 'NIT')], default='0', max_length=1)),
                ('idcode', models.CharField(max_length=50)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=35)),
                ('lastname', models.CharField(max_length=35)),
                ('identification', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=35)),
                ('state', models.BooleanField(default=True)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appweb.account')),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to=settings.AUTH_USER_MODEL)),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Website')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appweb.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=True, to='appweb.account_type'),
        ),
    ]
