# Generated by Django 2.0.4 on 2018-04-09 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_auto_20180408_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='country',
            name='createddate',
        ),
        migrations.RemoveField(
            model_name='country',
            name='lastmodifiedby',
        ),
        migrations.RemoveField(
            model_name='country',
            name='lastmodifieddate',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_country', to='appweb.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country')},
        ),
    ]
