# Generated by Django 2.0.4 on 2018-04-09 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_auto_20180408_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses_city', to='appweb.city', verbose_name='city'),
        ),
    ]
