# Generated by Django 2.0.4 on 2018-04-17 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65, verbose_name='Company Name')),
                ('comments', models.CharField(max_length=65)),
                ('type', models.CharField(choices=[('0', 'RUT'), ('1', 'NIT')], default='0', max_length=1, verbose_name='Ref type')),
                ('idcode', models.CharField(db_index=True, max_length=50, verbose_name='Ref number')),
                ('payment_duedays', models.IntegerField(default=0, verbose_name='Payment due days')),
                ('address', models.CharField(default='', max_length=30, verbose_name='Address')),
                ('addressnumber', models.CharField(default=0, max_length=6, verbose_name='Address number')),
                ('city', models.CharField(default='', max_length=65, verbose_name='City')),
                ('state', models.CharField(default='', max_length=30, verbose_name='State')),
                ('country', models.CharField(default='CHILE', max_length=65, null=True, verbose_name='Country')),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=0, max_length=6, verbose_name='Country code')),
                ('name', models.CharField(max_length=255, verbose_name='Country name')),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
