# Generated by Django 2.0.4 on 2018-04-17 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65, verbose_name='Account name')),
                ('accountnumber', models.CharField(max_length=50, verbose_name='Account number')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='acc_company', to='appweb.company', verbose_name='Parent company')),
                ('aliquot', models.FloatField(verbose_name='Aliquot')),
                ('slug', models.SlugField(null=True)),
                ('address', models.CharField(default='', max_length=30, verbose_name='Address')),
                ('addressnumber', models.CharField(default=0, max_length=6, verbose_name='Address numner')),
                ('city', models.CharField(default='', max_length=65, verbose_name='City')),
                ('state', models.CharField(default='', max_length=30, verbose_name='State')),
                ('country', models.CharField(default='CHILE', max_length=65, null=True, verbose_name='Country')),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_user', to=settings.AUTH_USER_MODEL)),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='account_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acctype_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acctype_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Account type',
                'verbose_name_plural': 'Account types',
            },
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Address')),
                ('zip', models.IntegerField(verbose_name='zip/postal code')),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='City name')),
                ('code', models.IntegerField(verbose_name='City Code')),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_country', to='appweb.country', verbose_name='Country')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=35)),
                ('lastname', models.CharField(max_length=35)),
                ('identification', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=35)),
                ('state', models.BooleanField(default=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appweb.account')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_user', to=settings.AUTH_USER_MODEL)),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Website')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appweb.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses_city', to='appweb.city', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='address',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='address',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=True, to='appweb.account_type', verbose_name='Account Type'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('firstname', 'lastname')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('name', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'accountnumber')},
        ),
    ]
