# Generated by Django 2.0.4 on 2018-04-18 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_auto_20180417_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contactmain',
            field=models.CharField(max_length=45, null=True, verbose_name='Contact main'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='company',
            name='startdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='totalcondominium',
            field=models.IntegerField(default=0, verbose_name='Total number Condominiums'),
        ),
        migrations.AddField(
            model_name='company',
            name='totaltown',
            field=models.IntegerField(default=0, verbose_name='Total number Town'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=65, unique=True, verbose_name='Company Name'),
        ),
    ]
