# Generated by Django 2.0.4 on 2018-04-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_auto_20180417_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='phonenumber',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='company',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
