# Generated by Django 2.0.4 on 2018-04-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_auto_20180417_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url page'),
        ),
    ]
