# Generated by Django 2.0.4 on 2018-04-18 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appweb', '0006_auto_20180417_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unitnumber', models.CharField(max_length=50, verbose_name='Unit number')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='unit_company', to='appweb.company', verbose_name='Parent company')),
                ('aliquot', models.FloatField(verbose_name='Aliquot')),
                ('comments', models.TextField(blank=True, null=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_user', to=settings.AUTH_USER_MODEL)),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountnumber',
            field=models.CharField(db_index=True, max_length=18, unique=True, verbose_name='Account number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='addressnumber',
            field=models.CharField(default=0, max_length=6, verbose_name='Address number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=True, related_name='acc_acctype', to='appweb.account_type', verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='account_type',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(on_delete=True, to='appweb.account_type', verbose_name='Account Type'),
        ),
        migrations.RemoveField(
            model_name='account',
            name='aliquot',
        ),
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('type', 'unitnumber')},
        ),
    ]
