# Generated by Django 2.0.4 on 2018-04-08 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dateoperation', models.DateTimeField(default=django.utils.timezone.now)),
                ('datevalue', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(default=0.0)),
                ('transcode', models.CharField(max_length=18)),
                ('description', models.CharField(max_length=60)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bank_account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=12)),
                ('label', models.CharField(max_length=30, unique=True)),
                ('entity', models.IntegerField(default=1)),
                ('bankcode', models.CharField(max_length=125, unique=True)),
                ('number', models.CharField(max_length=255)),
                ('accountnumber', models.CharField(max_length=30)),
                ('accountcurrent', models.CharField(max_length=10)),
                ('mim_allowed', models.FloatField(default=0, max_length=11)),
                ('mim_desired', models.FloatField(default=0, max_length=11)),
                ('comments', models.TextField()),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='bankaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.bank_account'),
        ),
    ]
