# Generated by Django 2.0.4 on 2018-04-09 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appweb', '0009_auto_20180408_2235'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trans',
            fields=[
                ('transcode', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dateoperation', models.DateTimeField(default=django.utils.timezone.now)),
                ('datevalue', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=60)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.RemoveField(
            model_name='bank',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bankaccount',
        ),
        migrations.RemoveField(
            model_name='bank_account',
            name='id',
        ),
        migrations.AddField(
            model_name='bank_account',
            name='companyid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appweb.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='bankcode',
            field=models.CharField(max_length=125, unique=True, verbose_name='Bank Code'),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='label',
            field=models.CharField(max_length=30, unique=True, verbose_name='Label Bank Account'),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='number',
            field=models.CharField(max_length=255, verbose_name='Number Bank Account'),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='reference',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Reference Bank Account'),
        ),
        migrations.DeleteModel(
            name='bank',
        ),
        migrations.AddField(
            model_name='trans',
            name='bankaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.bank_account'),
        ),
        migrations.AddField(
            model_name='trans',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trans',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='trans',
            unique_together={('transcode', 'date')},
        ),
    ]
