# Generated by Django 2.0.4 on 2018-04-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180408_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trans',
            name='transcode',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='Trans Code Ref'),
        ),
    ]
