# Generated by Django 2.0.4 on 2018-04-09 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0003_auto_20180408_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank_account',
            options={'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
        migrations.RenameField(
            model_name='bank_account',
            old_name='modifieddate',
            new_name='lastmodifieddate',
        ),
        migrations.AddField(
            model_name='bank_account',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bankacc_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bankacc_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bank_account',
            unique_together={('reference', 'label')},
        ),
    ]
