# Generated by Django 2.0.4 on 2018-04-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20180408_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_account',
            old_name='accountcurrent',
            new_name='accountcurrency',
        ),
        migrations.RemoveField(
            model_name='bank_account',
            name='accountnumber',
        ),
    ]
