# Generated by Django 2.0.4 on 2018-04-09 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0005_auto_20180408_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trans',
            name='author',
        ),
        migrations.AddField(
            model_name='trans',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transowner_user', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
