# Generated by Django 2.0.7 on 2018-07-19 02:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='Account name')),
                ('accountnumber', models.CharField(db_index=True, max_length=18, unique=True, verbose_name='Account number')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='acc_company', to='siba.company', verbose_name='Parent company')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('address', models.CharField(default='', max_length=30, verbose_name='Address')),
                ('addressnumber', models.CharField(default=0, max_length=6, verbose_name='Address number')),
                ('city', models.CharField(default='', max_length=65, verbose_name='City')),
                ('state', models.CharField(default='', max_length=30, verbose_name='State')),
                ('country', models.CharField(default='CHILE', max_length=65, null=True, verbose_name='Country')),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_user', to=settings.AUTH_USER_MODEL)),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='account_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acctype_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acctype_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Account type',
                'verbose_name_plural': 'Account types',
            },
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Address')),
                ('zip', models.IntegerField(verbose_name='zip/postal code')),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='City name')),
                ('code', models.IntegerField(verbose_name='City Code')),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=65, unique=True, verbose_name='Company Name')),
                ('comments', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('type', models.CharField(choices=[('0', 'RUT'), ('1', 'NIT')], default='0', max_length=1, verbose_name='Ref type')),
                ('idcode', models.CharField(db_index=True, max_length=50, verbose_name='Ref number')),
                ('startdate', models.DateField(null=True)),
                ('payment_duedays', models.IntegerField(default=0, verbose_name='Payment due days')),
                ('address', models.CharField(default='', max_length=30, verbose_name='Address')),
                ('AddressNumber', models.CharField(default=0, max_length=6, verbose_name='Address number')),
                ('city', models.CharField(default='', max_length=65, verbose_name='City')),
                ('state', models.CharField(default='', max_length=30, verbose_name='State')),
                ('country', models.CharField(default='CHILE', max_length=65, null=True, verbose_name='Country')),
                ('totaltown', models.IntegerField(default=0, verbose_name='Total number Town')),
                ('totalcondominium', models.IntegerField(default=0, verbose_name='Total number Condominiums')),
                ('contactmain', models.CharField(max_length=45, null=True, verbose_name='Contact main')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url page')),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=35)),
                ('lastname', models.CharField(max_length=35)),
                ('identification', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=35)),
                ('state', models.BooleanField(default=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siba.account')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_user', to=settings.AUTH_USER_MODEL)),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=0, max_length=6, verbose_name='Country code')),
                ('name', models.CharField(max_length=255, verbose_name='Country name')),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unitnumber', models.CharField(max_length=50, verbose_name='Unit number')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='unit_company', to='siba.company', verbose_name='Parent company')),
                ('aliquot', models.FloatField(verbose_name='Aliquot')),
                ('comments', models.TextField(blank=True, null=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_user', to=settings.AUTH_USER_MODEL)),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_modifiers', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=True, to='siba.account_type', verbose_name='Account Type')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Website')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siba.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='company',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_country', to='siba.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='city',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses_city', to='siba.city', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='address',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='address',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=True, related_name='acc_acctype', to='siba.account_type', verbose_name='Account Type'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('type', 'unitnumber')},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('firstname', 'lastname')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('name', 'city')},
        ),
    ]
