# Generated by Django 2.0.4 on 2018-04-17 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appweb', '0002_auto_20180417_1631'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_account',
            fields=[
                ('accountreference', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Reference Bank Account')),
                ('accountlabel', models.CharField(max_length=30, unique=True, verbose_name='Label Bank Account')),
                ('bankname', models.CharField(max_length=60, verbose_name='Bank Name')),
                ('bankcode', models.CharField(max_length=125, unique=True, verbose_name='Bank Code')),
                ('accountnumber', models.CharField(max_length=255, verbose_name='Number Bank Account')),
                ('accountcurrency', models.CharField(max_length=10)),
                ('mim_allowed', models.FloatField(default=0, max_length=11)),
                ('mim_desired', models.FloatField(default=0, max_length=11)),
                ('comments', models.TextField(null=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
                ('companyid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appweb.company', verbose_name='Company')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bankacc_user', to=settings.AUTH_USER_MODEL)),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bankacc_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='trans',
            fields=[
                ('transcode', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='Trans Code Ref')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dateoperation', models.DateTimeField(default=django.utils.timezone.now)),
                ('datevalue', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=60)),
                ('note', models.TextField(null=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
                ('bankaccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.bank_account')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_user', to=settings.AUTH_USER_MODEL)),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_modifiers', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transowner_user', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='trans',
            unique_together={('transcode', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='bank_account',
            unique_together={('accountreference', 'accountlabel')},
        ),
    ]
